name: Flutter Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.5.4"

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test --coverage
